apiVersion: v1
kind: Service
metadata:
  name: {{ include "dclaw-waste.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "dclaw-waste.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
